### ISSUE TITLE
Agregar tags a modelo "attachment"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#10]
Se requiere campo *tags* para el modelo *ir.attachment*. Es necesario para poder categorizar los documentos. Seguir las siguientes restricciones:
* Debe heredar de *ir.attachment*.
* Puede guiarse en el modelo *project.task* para agregar este campo.
* Tiempo estimado: 30 minutos.

**Comment by evazquez-gstd** [comment]
<h1>Se agrega tags a modelo "attachment"</h1>

![imagen](https://cloud.githubusercontent.com/assets/22351598/22002647/335cbe5c-dc13-11e6-9b2b-978a02d2c2d4.png)

**Comment by fmendoza-gstd** [comment]
Corregir las siguientes observaciones:

![captura de pantalla 2017-01-17 a las 9 54 11](https://cloud.githubusercontent.com/assets/22350992/22028105/af6cb578-dc9b-11e6-9dca-f29a94096d61.png)

**Comment by evazquez-gstd** [comment]
<h1>Anexo ajustes </h1>

Se crea archivo attachment y se cargan sus clases respectivamente.

![imagen](https://cloud.githubusercontent.com/assets/22351598/22043297/a0d33c7e-dcd4-11e6-9c16-d8e6b292e71b.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/22043271/8354e77e-dcd4-11e6-8ec4-805e3b467307.png)

**Comment by fmendoza-gstd** [comment]
Corregir las siguientes observaciones:

![captura de pantalla 2017-01-18 a las 9 46 07](https://cloud.githubusercontent.com/assets/22350992/22070942/4256e102-dd63-11e6-9389-42426dbf1ea5.png)

### Nota: Haga los cambios en código y vistas.

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22071985/7aa28900-dd66-11e6-9c80-2c5357ccad19.png)

**Comment by fmendoza-gstd** [comment]
La refactorización del último paso no esta completa.

**Comment by evazquez-gstd** [comment]
Ajustes en modelo y xml.

![imagen](https://cloud.githubusercontent.com/assets/22351598/22073139/1fc2ab6a-dd6a-11e6-876f-f0e8ba44a87f.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/22073028/cf5504e8-dd69-11e6-8f26-18c423acc477.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/22073050/dc4c98fa-dd69-11e6-9415-7f9b6daac33d.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/22073235/6d7672c4-dd6a-11e6-8ec9-9535c3a9610b.png)

**Comment by fmendoza-gstd** [comment]
👍
