### ISSUE TITLE
Generar reporte para contrato de venta

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#11]
Se requiere la capacidad para generar el contrato de venta en PDF. Restricciones:
* Usar y modificar la plantilla existente en el archivo *contract_views.xml*.
* Tiempo estimado: 1 horas.

**Comment by ivaldivia** [comment]
[Contrato(12).pdf](https://github.com/globalstandards/gpsi-erp/files/709576/Contrato.12.pdf)

**Comment by fmendoza-gstd** [comment]
Corregir las observaciones:

![captura de pantalla 2017-01-16 a las 17 16 19](https://cloud.githubusercontent.com/assets/22350992/22002252/11e0c960-dc10-11e6-845b-1fe088a6d704.png)

**Comment by ivaldivia** [comment]
[Contrato(19).pdf](https://github.com/globalstandards/gpsi-erp/files/711928/Contrato.19.pdf)

**Comment by ivaldivia** [comment]
Se agrego sale_data.xml con los registros de las categorías para los productos y clasificaarse al momento de generar el contrato por año.

- Annual 1

- Annual 2

- Annual 3

**Comment by ivaldivia** [comment]
Sobre la fecha le pregunté a Sandra Jiménez y me dijo que puede quedar para que lo llene el cliente al momento de firmar el contrato
