### ISSUE TITLE
Generar reporte para cotización de venta

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#12]
Se requiere la funcionalidad de imprimir el "cotización de venta" en PDF. Restricciones:
* Usar la plantilla oficial de GlobalSTD.
* Modificar la plantilla por defecto para imprimir cotizaciones de las ordenes de venta.
* Tiempo estimado: 2 horas.

**Comment by ivaldivia** [comment]
[Propuesta(36).pdf](https://github.com/globalstandards/gpsi-erp/files/714487/Propuesta.36.pdf)

Detalles de la actividad

- No se si esta bien el tamaño de las letras
- Los siguientes campos se obtendran del Application Form?: Rango de empleados, Aplica diseño, Tipo de certificación,  Comentarios Adicionales 
- Emisión de certificado y mantenimeinto de certificado como se identificarán para omitir la cantidad?
