### ISSUE TITLE
Crear árbol de menú para staff

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#13]
#### **Requerimiento**
Se requiere un árbol de menu para el área de staff, la estructura debe ser la siguiente:

- Staff
   - Dashboard
   - Operations
      - Employees
      - Appraisals
      - Documents
   - Reports
      - Appraisals
   - Settings
      - Appraisal Plans

#### **Restricciones**

- Al hacer click en algún elemento "hoja" se debe mostrar el listado de contactos.
- La definición del menú debe estar en el archivo *general_views.xml*
- Tiempo estimado: 1 hora

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22078640/542db5e8-dd7e-11e6-8b2a-9e11ce07d56f.png)

**Comment by fmendoza-gstd** [comment]
#### Corregir las siguientes observaciones:

![captura de pantalla 2017-01-18 a las 13 07 54](https://cloud.githubusercontent.com/assets/22350992/22079171/7ad71d04-dd80-11e6-87bd-fe40eb90ce0f.png)

**Comment by fmendoza-gstd** [comment]
👍
