### ISSUE TITLE
Crear árbol de menu para training

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#14]
#### **Requerimiento**
Se requiere un árbol de menu para el área de training, la estructura debe ser la siguiente:

- Training
   - Dashboard
   - Operations
      - Employees
      - Appraisals
      - Documents
   - Reports
      - Appraisals
   - Settings
      - Appraisal Plans

#### **Restricciones**

- Al hacer click en algún elemento "hoja" se debe mostrar el listado de contactos.
- La definición del menú debe estar en el archivo *general_views.xml"
- Tiempo estimado: 1 hora

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by ivaldivia** [comment]
![arbol training](https://cloud.githubusercontent.com/assets/22351217/22079825/cca8cab8-dd82-11e6-9a12-7fc6aa155e70.png)

**Comment by fmendoza-gstd** [comment]
#### Corregir las siguientes observaciones:

![5d3d076c-dd86-11e6-92db-5783635d1eae](https://cloud.githubusercontent.com/assets/22350992/22082567/ef47a778-dd8d-11e6-8f3d-8c2e52cc95c8.png)

**Comment by fmendoza-gstd** [comment]
#### Corregir las observaciones siguientes:

- Los identificadores no siguen la convención, vea los ejemplos en la siguiente imagen:

![captura de pantalla 2017-01-18 a las 15 33 14](https://cloud.githubusercontent.com/assets/22350992/22083955/c24d58e8-dd93-11e6-8b40-34f02fd7d64e.png)

**Comment by fmendoza-gstd** [comment]
Marca error al actualizar.

**Comment by fmendoza-gstd** [comment]
#### Corregir las siguientes observaciones:

- Cambiar la estructura de tal manera que ahora sea:

```
- Training
   - Dashboard
   - Operations
      - Attendees   (Esta acción debe desplegar el modelo event.registration)
      - Events   (Esta acción debe desplegar el modelo event.event)
      - Documents Control
   - Reports
      - Events
   - Configuration
      - Settings
```

**Comment by fmendoza-gstd** [comment]
👍
