### ISSUE TITLE
Agregar opción skills a menu staff

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#15]
#### Requerimiento
Se requiere se agregue la opción *Skills* al menu Staff, ver la siguiente imagen:

![captura de pantalla 2017-01-18 a las 13 22 44](https://cloud.githubusercontent.com/assets/22350992/22079439/7407d5f8-dd81-11e6-8d8e-e204fd7faba1.png)

#### Reestricciones
- La acción debe usar el modelo *gpsi.staff.skill*.
- La acción debe mostrar las vistas *Tree y Form*.

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22083434/b894a2b8-dd91-11e6-9188-dedaeb7c5090.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/22083420/aec8cda4-dd91-11e6-96e1-81131477cec3.png)

**Comment by fmendoza-gstd** [comment]
#### Corregir las siguientes observaciones

- La opción "Skills" debe ser hijo de "Settings"

**Comment by evazquez-gstd** [comment]
Listo.

![imagen](https://cloud.githubusercontent.com/assets/22351598/22083746/004a5eee-dd93-11e6-9226-01aebd73aec9.png)

**Comment by fmendoza-gstd** [comment]
👍
