### ISSUE TITLE
Cambiar estructura de menú staff

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#16]
#### Requerimiento
Se requiere se cambie la estructura de menú *Settings*, actualmente es:
- Settings
   - Appraisal Plans
   - Skills

Debe cambiarse a:
- Configuration
   - Settings
   - Skills
   - Attachments
      - Tags (Nota: La acción de este menú debe mostrar el modelo ir.attachment.category)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22114485/4860bbe6-de2f-11e6-9266-dd891b42d6d5.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22115012/00e3fbdc-de31-11e6-89e2-c53c48b25b51.png)

**Comment by fmendoza-gstd** [comment]
👍
