### ISSUE TITLE
Agregar campo instructor a ficha de evento

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#17]
#### Requerimiento
Se requiere agregar campo para seleccionar al instructor del evento al modelo *event.event*.
- Modificar la vista por defecto para que muestre este campo.
- Tiempo estimado: 1 hora.

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by ivaldivia** [comment]
![instructor](https://cloud.githubusercontent.com/assets/22351217/22118945/450591d2-de3f-11e6-8525-fe1f6dc0c61e.png)

**Comment by fmendoza-gstd** [comment]
👍
