### ISSUE TITLE
Crear reporte "Lista de Asistentes"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#18]
#### Requerimiento
Se requiere reporte para generar lista de asistentes del evento seleccionado, el formato no fue proporcionado por lo tanto proponer uno.

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by ivaldivia** [comment]
[Lista de Asistentes(7).pdf](https://github.com/globalstandards/gpsi-erp/files/717841/Lista.de.Asistentes.7.pdf)
