### ISSUE TITLE
Control de requerimientos del área de Training [Reunión con Julio]

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#2]
Revisar con Julio de Training los avances realizados respecto a la automatización de sus procesos.

**Comment by ivaldivia** [comment]
- [x] Cursos con fecha quebrada

- [ ] Course Log

- [x] Tipo de Moneda

- [x] Campo de Instructor

- [ ] Candado de confirmación de asistentes, dependen de la confirmación del curso

- [x] Cancelación de asistentes y el impacto en facturación

- [ ] Imprimir: Lista de asistentes, caballetes, certificado, letrero de sala

- [x] Ajustar destinos de email

- [ ] Datos en la tabla de asistentes: 
+estado facturación
+aprobación
-evento
-ticket
+ejecutivo
+estado de envio de email

- [ ] Gestión de códigos

- [ ] Control de documentos / Repositorio (clasificación de carpetas)

- [ ] Competencias de instructor

- [ ] Encuesta de satisfacción

- [ ] Control de calificaciones

- [ ] Fecha limite de registro

- [ ] Elegir Certificado/Constancia/Ambos

**Comment by fmendoza-gstd** [comment]
#### Requerimiento
Reunirse con Julio a las 11:00, revisar los avances y solicitar documentación faltante, al final de la cita documentar en esta ficha los detalles importantes de la reunión.

**Comment by ivaldivia** [comment]
- [ ] Cambiar el formato de asistencia, varia en días y logos

- [ ] Ajuste de correo desde ventas, default 'company'

- [ ] El tipo de certificado será definido por asistente y no por curso

- [ ] Notificación a los participantes cuando se confirme el curso

- [ ] Encuesta de satisfacción cuando se termine el curso, con su respectivo reporte gráfico, son requerido para la emisión de certificado
