### ISSUE TITLE
Agregar campo para la politica de entrega de certificados

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#20]
#### Requerimientos
Se requiere agregar campo de tipo *Selection* y nombre *gs_certificate_delivery_policy* que indica la política de entrega de certificado para el asistente seleccionado. El campo debe tener los siguiente valores:
- Company
- Me
- Both

#### Restricciones
- El campo debe ser agregado al modelo *event.registration*.
- Modificar la vista por defecto para mostrar el campo.
- Tiempo estimado: 1 hora

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by ivaldivia** [comment]
![politica de entrega de certificado](https://cloud.githubusercontent.com/assets/22351217/22119936/1095c0e4-de43-11e6-8f41-011cbe6ededa.png)

**Comment by fmendoza-gstd** [comment]
👍
