### ISSUE TITLE
Crear vista para modelo del perfil profesional del empleado

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#22]
#### Requerimiento
Se requiere vista para el modelo del perfil profesional del usuario. Antes de iniciar esta tarea deberá de completar la tarea #21.

#### Consideraciones
- La definición de la vista deben estar en el archivo *hr_employee_profile_views.xml*.
- Tiempo estimado: 1 hora

[Para dudas aquí](https://appear.in/gpsi-erp-dev)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22157165/2a3a8570-defc-11e6-82bb-a75e15a7c159.png)

**Comment by fmendoza-gstd** [comment]
#### Corregir las siguientes observaciones

![captura de pantalla 2017-01-20 a las 11 29 09](https://cloud.githubusercontent.com/assets/22350992/22158935/3b588ebc-df04-11e6-9a42-205b906cb093.png)

![captura de pantalla 2017-01-20 a las 11 33 26](https://cloud.githubusercontent.com/assets/22350992/22158983/7e8ce64c-df04-11e6-8aa0-e7d684c99862.png)
