### ISSUE TITLE
Control de requerimientos del área de Staff

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#4]
Realizar las siguientes actividades:
* Reunirse con Zamir para revisar avances.
* Documentar resultados de la reunión sobre esta ficha.
* Tiempo estimado: 1 hora.

**Comment by evazquez-gstd** [comment]
Se revisaron los siguientes puntos como avances actuales de carga de documentos por usuario:
1.	Competence Requirement Criteria 
2.	Process map
3.	Witness
4.	Audit log (historial de auditorías por usuario)
5.	Manejo de documentos de formación (gestión de archivos del usuario por categoría)
6.	Exámenes periódicos
7.	Check de requerimientos para liberar IAF/SECTOR
Los avances mostrados contemplan la carga de documentación de los puntos (1, 2, 3, 5, 6)   para la acreditación de IAF, en la misma sección se dio a conocer el campo Tags para la categorización de documentos. Se presentó la vista para la carga de habilidades en la sección de competencias. (STATUS : EN PROCESO)
Del punto 4 de la minuta, se platicó acerca de una vista para visualizar en forma de lista un tracking de información respecto al histórico de auditorías por usuario. (STATUS : FALTA)
Los criterios para la liberación del IAF en automático contemplan los siguientes puntos.
1.	Que el auditor en cuestión tenga la experiencia ya en la competencia.
2.	Que el auditor cumpla con un mínimo de 4 auditorías para la competencia.
3.	Que el auditor tenga acreditado su examen de competencias “Standard”. (Process Map)
Aún falta información de documentos anexos

**Comment by fmendoza-gstd** [comment]
👍
