### ISSUE TITLE
Agregar vista para modelo "skill"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#7]
Se requiere vistas para el modelo *skill*:
* Agregar vistas en el archivo *skill_views.xml*
* Agregar vistas de tipo *List* y *Form*
* Tiempo estimado: 1 hora

**Comment by evazquez-gstd** [comment]
<h1>Anexo Vistas de Skills</h1>

![imagen](https://cloud.githubusercontent.com/assets/22351598/21995532/0d678894-dbeb-11e6-9608-6a9f617af777.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21995549/26372afa-dbeb-11e6-8776-11ff5e44ed4a.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
