### ISSUE TITLE
Agregar vista para modelo de contrato de venta

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#8]
Se requiere la vista para un contrato de venta. Restricciones:
* Extender la vista por defecto de *sale.order*
* Tiempo estimado: 1:30 hora

**Comment by ivaldivia** [comment]
![vista contrato 1](https://cloud.githubusercontent.com/assets/22351217/21994956/f92845d8-dbe7-11e6-95ca-d27b1a275e68.png)
![vista contrato 2](https://cloud.githubusercontent.com/assets/22351217/21994962/fdda58a0-dbe7-11e6-979c-2cfa4bf3dd5f.png)

**Comment by fmendoza-gstd** [comment]
Realizar los siguientes cambios:

![f92845d8-dbe7-11e6-95ca-d27b1a275e68](https://cloud.githubusercontent.com/assets/22350992/21995206/3b8ac92c-dbe9-11e6-83d3-d75581107980.png)

![fdda58a0-dbe7-11e6-979c-2cfa4bf3dd5f](https://cloud.githubusercontent.com/assets/22350992/21995271/8e391da4-dbe9-11e6-944d-92c8735b6f55.png)

**Comment by ivaldivia** [comment]
![vista contrato 3](https://cloud.githubusercontent.com/assets/22351217/21995832/acf4fde6-dbec-11e6-98b8-ab34b0a0aa3b.png)
![vista contrato 4](https://cloud.githubusercontent.com/assets/22351217/21995833/acf74114-dbec-11e6-9492-de764ec94eeb.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
