### ISSUE TITLE
Agregar botón a documento de empleado

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-erp#9]
Se requiere botón que al ser presionado muestre todos los documentos asociados al empleado.

![](https://www.odoo.com/apps/modules/9.0/hr_employee_documents/employee_documents.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/22045901/ce870020-dce2-11e6-8e87-47a18bbcc951.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/22045924/f6ddf114-dce2-11e6-87c8-16f32f4d056c.png)

**Comment by fmendoza-gstd** [comment]
👍
